name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE (#$NUMBER) — @$AUTHOR'
change-title-escapes: '\<*_&'
exclude-labels:
  - 'skip-changelog'
  - 'dependencies'
  - 'release'
autolabeler:
  - label: 'feature'
    branch:
      - '/^feat\/.+/'
    title:
      - '/^feat(\(.+\))?:/i'
  - label: 'bug'
    branch:
      - '/^fix\/.+/'
    title:
      - '/^fix(\(.+\))?:/i'
  - label: 'chore'
    branch:
      - '/^chore\/.+/'
    title:
      - '/^chore(\(.+\))?:/i'
  - label: 'docs'
    branch:
      - '/^docs\/.+/'
    title:
      - '/^docs(\(.+\))?:/i'
categories:
  - title: '🚀 Features'
    labels: ['enhancement', 'feature']
  - title: '🐛 Bug Fixes'
    labels: ['bug', 'fix']
  - title: '🧹 Maintenance'
    labels: ['chore', 'docs']
  - title: '📦 Other Changes'
version-resolver:
  major:
    labels: ['breaking']
  minor:
    labels: ['enhancement', 'feature']
  patch:
    labels: ['bug', 'fix', 'chore', 'docs']
  default: patch
template: |
  ## What's Changed
  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
